### ISSUE TITLE
Making rtf-files of the last 20 emails

### ISSUE THREAD

**Issue by tiila** [melaeli/kik-lg211-classification-final#10]
S

**Comment by melaeli** [comment]
The readpst command to the .pst email file made 2 file types from every email: extentionless file and .rtf file (just the body text). Some of the emails do not have .rtf files - we will skip those for now from our data ie. files/emails 1-6 and 51-72. We'll get back to those possibly later...

**Comment by melaeli** [comment]
"Making rtf-files of the last 20 emails" I don't know or remember what this means...maybe about those missing .rtf files. Actually, correction to the previous comment, also those emails are in data but they are not used because of the code.
