### ISSUE TITLE
Updating Github

### ISSUE THREAD

**Issue by melaeli** [melaeli/kik-lg211-classification-final#15]

**Comment by melaeli** [comment]
Elina done (situation at 11pm, 4 Dec 18)

**Comment by melaeli** [comment]
Remember to put the final code in the GitHub and send the emails data by email.

**Comment by melaeli** [comment]
The email data sent by email to Mathias and Dima. **Please don't share the material while it may contain my personal information. Thanks!**
And it was impossible to attach the Apache Tika file even compressed because of its big size but you can find it (version tika-app-1.19.1.jar) here: https://archive.apache.org/dist/tika/

**Comment by melaeli** [comment]
index.html and flaskdemo.py pushed into GitHub (situation 28.12.2018)

**Comment by melaeli** [comment]
schema.xml (changed) and solrconfig.xml (unchanged) pushed into GitHub (situation 29.12.2018)
#32

**Comment by tiila** [comment]
No actions needed.
