### ISSUE TITLE
Search words and comments on them

### ISSUE THREAD

**Issue by melaeli** [melaeli/kik-lg211-classification-final#16]
Data includes commercial emails from the following categories:

Black Friday

Joulu / kesä

Naiset / miehet (-> morfological analysis?)

Vaatteet (esim. neuleet)

Tapahtuma / kokous

Hotelli

Matka

Koulutus / viestintä

Kielenhuolto

Ravintola / lounas / viini

Lahjakortti / elämys

Liikunta (esim. liikuttaa) / terveys (esim. hedelmä)

Sulkuturva

Merkkituote

Tarjous

Lahja

**Comment by melaeli** [comment]
Black Friday
Black tai Friday ei tulosta
Black Friday 
-> urllib.error.HTTPError: HTTP Error 400: Illegal character SPACE=' ')

Joulu / joulu
OK
Huom. ääkköset (kuten myös hotelli-haulla * ):
VielÃ¤ ehdit tilata Delicard-lahjakortit iloisella joulutervehdyksellÃ¤.
vs.
Hauskat pikkujoulut standup-illassa - Tunnelmallinen joululevy tyylikkääksi liikelahjaksi!


Kesä / kesä 
-> UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 33: ordinal not in range(128)

Naiset / miehet (-> morfologinen analyysi?) 
ei tulosta

Vaatteet (esim. neuleet)
ei tulosta

Tapahtuma / kokous
löytää myös katkaistun sanan sekä pienellä tai isolla alkukirjaimella: 
[Aa]siakastapahtuma löytää asiakastapahtuman

Hotelli
OK paitsi *

Matka
OK

Koulutus / viestintä
OK / UnicodeEncodeError

Kielenhuolto
ei tulosta: kielenhu, kielenhuo, kielenhuol, kielenhuolt
OK tulos kielenhuolto, vaikka tekstissä vain sana kielenhuoltoa

Ravintola / lounas / viini

Lahjakortti / elämys

Liikunta (esim. liikuttaa) / terveys (esim. hedelmä)

Sulkuturva

Merkkituote:
antaa hakutuloksen, vaikka tekstissä vain sana merkkituotteita; ei tulosta merkkituot

Tarjous

Lahja

Huom. Testi-hakusana antaa:
Aloita hedelmÃ¤inen helmikuu
VAIKKA teksti ei sisällä testi-sanaa

**Comment by melaeli** [comment]
1) The search finds also the cut word both with small or big letter p.ex. [Aa]siakastapahtuma finds asiakastapahtuman

2) Testi search word gives: "Aloita hedelmÃ¤inen helmikuu" email even if the text doesn'd include the word testi
and 
Merkkituote search word gives a result even if there's only the word merkkituotteita in the text (no result for merkkituot)

-> They have the same word body which can be checked in Solr - Analyze

**Comment by melaeli** [comment]
The search with numbers work as they are found and gives no error but p.ex. the search for 10, "10", "10 " always gives also the 10, 100, 1000... And the search for 200 gives also the results with only 20. Having the euro sign after the number makes no difference.

**Comment by melaeli** [comment]
Look #25

The search with joulu -> 10 results but
the search with joul* or joulu* -> 21 results even if with joulu it should be the same amount...

I tried to check the Analyze in Solr but not quite sure why it's working like this.

**Comment by melaeli** [comment]
Some of the common words like JA and OVAT don't work in the search because Solr stemms them into nothing.

**Comment by tiila** [comment]
This was used for demoing of the project.
