### ISSUE TITLE
Correcting the encoding problem with some of the subjects

### ISSUE THREAD

**Issue by melaeli** [melaeli/kik-lg211-classification-final#26]

**Comment by melaeli** [comment]
In 5 email subjects there's a problem with encoding. At class with Dima we found out that the problem is in -j in the following command:

$ java -jar tika-app-1.19.1.jar -j 32 > 32testi.json

We tried a couple of different commands like:
$ java -Dfile.encoding=utf-8 -jar tika-app-1.19.1.jar -j 32 > 32testi.json

But they didn't work. We leave it now like this and concentrate on different tasks...

**Comment by melaeli** [comment]
I asked some help (Miikka) with this encoding problem anyway and got an answer:

- Ääkköset are encoded differently in subjects and body texts in these few emails.

- In the email 15 the subject is utf-8 but the body text is Latin 1 (eli iso-8859-1).

- The email 32 is entirely utf-8 but Tika probably recognizes wrongly the encoding of the subject as Latin 1. This may be because there is a warning in the meta data:

X-Amavis-Alert: BAD HEADER, Non-encoded 8-bit data (char F6 hex): Subject:
        My\366nteinen j\344m\344kk\344[...]

- In the email 39 the subject is some kind of ASCII representation from Latin 1 encoding:

=?iso-8859-1?Q?Irtiotto_arjesta_-_vinkkej=E4_ja_vaikutteita_kev=E4=E4n_ko?=

and the body text is windows-1252 encoding (the own version of the Windows from the Latin 1 encoding). This Tika apparantely can handle correctly.

- Not quite sure how to fix this. Maybe with the email 32 you should say to Tika that don't convert the encoding at all. With the email 15 you should say to Tika that convert the subject but don't do anything with the body text.

So IF we have time left after other improvements, we could check this out :)

**Comment by DmitryKey** [comment]
Hello,

The general approach to fixing these issues is to basically convert ascii (or win-1252) to utf-8 using iconv utility (usually part of linux): https://en.wikipedia.org/wiki/Iconv

**Comment by tiila** [comment]
This is still a relevant issue we would have liked to solved but it stays unsolved.
