### ISSUE TITLE
Modifying the theme extractor or clustering: preprocessing data

### ISSUE THREAD

**Issue by melaeli** [melaeli/kik-lg211-classification-final#5]
L
https://github.com/DmitryKey/kik-lg211-2018/blob/master/nlp-demos/themes/themes_extractor.py
Preprocessing Finnish data as the extractor does not support Finnish.

**Comment by melaeli** [comment]
If we choose to do the themes extraction, add some more commercial emails into the data.

**Comment by tiila** [comment]
This issue had become irrelevant as we did not apply themes extraction.
